FROM node:alpine

WORKDIR /usr/users-api

COPY package.json tsconfig.json ./

RUN npm install && npm cache clean --force && npm install -g typescript

COPY . .

RUN tsc

CMD ["node", "./build/src/server.js"]