FROM node:alpine

WORKDIR /usr/auth-api

COPY package.json tsconfig.json ./

RUN npm install && npm cache clean --force && npm install -g typescript

COPY . .

RUN tsc

CMD ["node", "./build/server.js"]